name: Continuous integration 📝

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  merge_group:
    types: [checks_requested]
  workflow_dispatch: {}

jobs:
  # Check if changes were made to the relevant files.
  # Always returns true if running on the default branch, to ensure all changes are thoroughly checked.
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/check-changes
        id: filter

  check:
    needs: changes
    if: ${{ needs.changes.outputs.markdown == 'true' }}
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: rvben/rumdl@v0.2.22

  # This is a meta job to mark successful completion of the required checks,
  # even if they are skipped due to no changes in the relevant files.
  required-checks:
    name: Required checks 📝
    needs: [
      changes,
      check,
    ]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Fail if required checks failed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: |
          echo "Required checks failed"
          echo "Please check the logs for more information"
          exit 1
      - name: Pass if all required checks passed
        run: |
          echo "All required checks passed"
